language: C
compiler:
  - clang
  - gcc
script: make && make test
before_install:
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.3.0.tar.gz -O libtf.tar.gz
  - sudo tar -C /usr/local -xzf libtf.tar.gz
  - sudo ldconfig
  - wget https://github.com/ray1422/Fantastic-Filter-CLI/releases/download/v0.0.1-alpha/FF_Model.tar.gz
  - tar -xvf FF_Model.tar.gz -C ~/

env:
  - FF_MODEL_PATH=~/FF_Model

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t fantastic-filter-cli .
        - docker images
        - docker tag fantastic-filter-cli $DOCKER_USERNAME/fantastic-filter-cli:latest
        - docker push $DOCKER_USERNAME/fantastic-filter-cli:latest
    - stage: Docker Test
      script: docker run --rm $DOCKER_USERNAME/fantastic-filter-cli:latest ff-cli -b=0
