language: C
compiler: gcc
script: make && make test
before_install:
  - wget https://storage.googleapis.com/tensorflow-nightly/github/tensorflow/lib_package/libtensorflow-cpu-linux-x86_64.tar.gz -O libtf.tar.gz
  - sudo tar -C /usr/local -xzf libtf.tar.gz
  - sudo ldconfig
  - wget https://github.com/ray1422/Fantastic-Filter-CLI/releases/download/v0.0.1-alpha/FF_Model.tar.gz
  - tar -xvf FF_Model.tar.gz -C ~/

env:
  - FF_MODEL_PATH=~/FF_Model