language: C
compiler: gcc
script: make
before_install:
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.3.0.tar.gz -O libtf.tar.gz
  - sudo tar -C /usr/local -xzf libtf.tar.gz
  - sudo ldconfig